
export enum ErrorCode {
  TODO_TITLE_REQUIRED = 'TODO_TITLE_REQUIRED',
  TODO_NOT_FOUND = 'TODO_NOT_FOUND',
  USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED',
  INVALID_TODO_ID = 'INVALID_TODO_ID',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}